include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Const correctness
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const

    # Code hygiene
    - always_declare_return_types
    - avoid_print
    - avoid_empty_else
    - avoid_unnecessary_containers
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - depend_on_referenced_packages
    - use_key_in_widget_constructors

    # Style and best practices
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - avoid_field_initializers_in_const_classes
    - prefer_expression_function_bodies
    - unnecessary_this
    - directives_ordering

    # Error prevention
    - avoid_init_to_null
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - null_closures
    - always_put_control_body_on_new_line
